### ISSUE TITLE
Documentation of coding standards

### ISSUE THREAD

**Issue by arianafrench** [amnh-library/API-Portal#20]
From 5/15 tech check-in: Establish coding standards, Git workflows, and any other necessary details for working with developer community.

**Comment by mik3caprio** [comment]
Git workflows and deploy procedures have been documented in the [API wiki](https://github.com/amnh-library/API-Portal/wiki) and the [Metasearch wiki](https://github.com/amnh-library/metasearch/wiki). We will have to defer coding standards for when we have more active contributors on the project.
