### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by arianafrench** [amnh-library/API-Portal#23]
Directed by IT, @samueltran, @mik3caprio along with Ben Virgilio.

**Comment by mik3caprio** [comment]
Should we add Ben to the GitHub repositories / team?

**Comment by samueltran** [comment]
Hi @mik3caprio, we can add Ben to the repo, but I am not sure whether it is necessary as he won't be doing any code review per se. The most important is that we provide a software architecture diagram, grant him access to the app, and show him a demo of the app.

**Comment by mik3caprio** [comment]
Myself @samueltran, @jrcwiok, and @pdelong42 met with Ben and reviewed security concerns and everything was deemed satisfactory.
