### ISSUE TITLE
VM funding

### ISSUE THREAD

**Issue by mik3caprio** [amnh-library/API-Portal#3]
Contact Tom B for info on funding for VMs for production

**Comment by jrcwiok** [comment]
Tom approved the funding for the dev VMs - Sam is taking care of the rest. How many production VMs do we need? 2?

**Comment by mik3caprio** [comment]
I would suggest 2, a production ElasticSearch and a production application server. @samueltran

**Comment by samueltran** [comment]
@mik3caprio @jrcwiok If you are ok with the possible outage caused by the failure of either server role, two VMs would be sufficient. @pdelong42, we need to estimate the time to rebuild for the SLAs. Thanks.

**Comment by mik3caprio** [comment]
I think since we're internal only for the foreseeable future, that's fine for now - and I'm assuming we can scale up later when we figure out things like the API proxy service, load balancing and such.
